import { MarketingNav, Footer } from "../../components/marketing";
import { Badge } from "../../components/ui/Badge";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-paper flex flex-col">
      <MarketingNav />
      
      <main className="flex-grow pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="mb-12">
            <Badge variant="neutral" className="mb-4">Legal Dossier</Badge>
            <h1 className="font-heading text-4xl sm:text-5xl font-bold text-ink mb-4">
              Terms of Service
            </h1>
            <p className="text-ink-subtle font-mono text-sm">
              Last Updated: January 2026
            </p>
          </div>

          {/* Legal Content */}
          <div className="prose prose-slate max-w-none text-ink-subtle">
            <section className="mb-8">
              <h2 className="font-heading text-xl font-semibold text-ink mb-3">1. Agreement to Terms</h2>
              <p className="mb-4">
                By accessing or using CartHost, you agree to be bound by these Terms of Service and our Privacy Policy. If you disagree with any part of the terms, you may not access the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="font-heading text-xl font-semibold text-ink mb-3">2. Description of Service</h2>
              <p className="mb-4">
                CartHost provides a "Liability-First" operational dashboard for property hosts ("Hosts") to manage amenity rentals. We provide tools for waivers, inspection logging, and evidence storage ("The Service").
              </p>
              <p className="mb-4 bg-surface p-4 rounded-md border border-rule border-l-4 border-l-accent-ops">
                <strong>Important Note:</strong> CartHost is a technology provider, not a law firm or insurance carrier. The waivers and evidence packets generated by our platform are tools for your operations, but we do not guarantee their legal enforceability in your specific jurisdiction.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="font-heading text-xl font-semibold text-ink mb-3">3. Host Responsibilities</h2>
              <p className="mb-4">
                As a Host using CartHost, you acknowledge that you are solely responsible for:
              </p>
              <ul className="list-disc pl-5 space-y-2 mb-4">
                <li>Ensuring your rental assets (golf carts, e-bikes, etc.) are safe and maintained.</li>
                <li>Verifying that your waivers comply with local and state laws.</li>
                <li>Obtaining appropriate insurance coverage for your rentals.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="font-heading text-xl font-semibold text-ink mb-3">4. Limitation of Liability</h2>
              <p className="mb-4">
                To the maximum extent permitted by law, CartHost shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including property damage or personal injury resulting from the use of your rental assets.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="font-heading text-xl font-semibold text-ink mb-3">5. Beta Access</h2>
              <p className="mb-4">
                Services labeled as "Beta" are provided "as is" and may contain bugs. We reserve the right to modify or discontinue features at any time during the beta period.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
